### PR TITLE
feature(repeat): Introduce iteration with a repeat feature

### PR DESCRIPTION
**Pull request by danielpetisme**
Update the syntax to process to abstract instruction name, fo,ba,etc are managed by the runtime
Build an IR representation of the BugHunts lang
Visit IR representation to trigger the runtime actions
Raise a basic compilation exception when parsing failed to be able to test compilation issues

This feature permits to write 

```
(FO RI) 4
```

which would be equivalent to 

```
FO RI FO RI FO RI FO RI
```

Note:
Is no more possible to do `FO 4`, you should write `(FO) 4` which is much more consistent with the syntax definition.

Thoughts?

### CODE REVIEW

**Comment by PierrePIRONIN** [comment]
Amazing ! Ok for me.

FO 4 will be authorized in the web application to be consistent with the board game, so we'll have to translate it into (FO) 4 before passing it to the parser but it's fine.

**Comment by jbouny** [comment]
Great :).

We will need to check if the computed number of instructions of a command is coherent to the physical board game.

**Comment by danielpetisme** [comment]
So far, the repeat instruction is transparent for the ladybug. I didn't add a specific "event" to that. 
Don't know if you need one for thé score computation ?

**Comment by PierrePIRONIN** [comment]
I just saw your last comment. I implement score computation in commit ba7805c7243c78033e245edd510b89db782f8a61

**Pull request merged**
